In [2]:
# 4.1 The NumPy ndarray: A Multidimensional Array Object


In [ ]:
In [7]: import numpy as np

In [3]:
In [8]: my_arr = np.arange(1_000_000)

In [4]:
In [9]: my_list = list(range(1_000_000))

In [7]:
In [10]: %timeit my_arr2 = my_arr * 2

763 μs ± 14.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
In [11]: %timeit my_list2 = [x * 2 for x in my_list]

25.1 ms ± 616 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
In [12]: import numpy as np

In [10]:
In [13]: data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [11]:
In [14]: data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [12]:
In [15]: data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [13]:
In [16]: data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [14]:
In [17]: data.shape

(2, 3)

In [15]:
In [18]: data.dtype

dtype('float64')

In [16]:
In [19]: data1 = [6, 7.5, 8, 0, 1]

In [17]:
In [20]: arr1 = np.array(data1)

In [18]:
In [21]: arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
In [22]: data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [20]:
In [23]: arr2 = np.array(data2)

In [21]:
In [24]: arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
In [25]: arr2.ndim

2

In [23]:
In [26]: arr2.shape

(2, 4)

In [24]:
In [27]: arr1.dtype

dtype('float64')

In [25]:
In [28]: arr2.dtype

dtype('int64')

In [26]:
In [29]: np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
In [30]: np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
In [31]: np.empty((2, 3, 2))

array([[[-3.10503618e+231, -1.44663096e-315],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  4.47032019e-038]],

       [[ 7.73184650e-091,  1.71696216e+185],
        [ 1.28241139e+160,  5.55149409e+170],
        [ 3.99910963e+252,  8.34402841e-309]]])

In [29]:
In [32]: np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
In [33]: arr1 = np.array([1, 2, 3], dtype=np.float64)

In [31]:
In [34]: arr2 = np.array([1, 2, 3], dtype=np.int32)

In [32]:
In [35]: arr1.dtype

dtype('float64')

In [33]:
In [36]: arr2.dtype

dtype('int32')

In [34]:
In [37]: arr = np.array([1, 2, 3, 4, 5])

In [35]:
In [38]: arr.dtype

dtype('int64')

In [36]:
In [39]: float_arr = arr.astype(np.float64)

In [37]:
In [40]: float_arr

array([1., 2., 3., 4., 5.])

In [38]:
In [41]: float_arr.dtype

dtype('float64')

In [39]:
In [42]: arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [40]:
In [43]: arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [41]:
In [44]: arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [60]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [44]:
In [47]: int_array = np.arange(10)

In [45]:
In [48]: calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [46]:
In [49]: int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
In [50]: zeros_uint32 = np.zeros(8, dtype="u4")

In [48]:
In [51]: zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [49]:
In [52]: arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [50]:
In [53]: arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [51]:
In [54]: arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [52]:
In [55]: arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
In [56]: 1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [54]:
In [57]: arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
In [58]: arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [56]:
In [59]: arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [57]:
In [60]: arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [58]:
In [61]: arr = np.arange(10)

In [59]:
In [62]: arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
In [63]: arr[5]

np.int64(5)

In [62]:
In [64]: arr[5:8]

array([5, 6, 7])

In [63]:
In [65]: arr[5:8] = 12

In [64]:
In [66]: arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [65]:
In [67]: arr_slice = arr[5:8]

In [66]:
In [68]: arr_slice

array([12, 12, 12])

In [67]:
In [69]: arr_slice[1] = 12345

In [68]:
In [70]: arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [69]:
In [71]: arr_slice[:] = 64

In [70]:
In [72]: arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [71]:
In [73]: arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [72]:
In [74]: arr2d[2]

array([7, 8, 9])

In [73]:
In [75]: arr2d[0][2]

np.int64(3)

In [74]:
In [76]: arr2d[0, 2]

np.int64(3)

In [75]:
In [77]: arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [76]:
In [78]: arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
In [79]: arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
In [80]: old_values = arr3d[0].copy()

In [79]:
In [81]: arr3d[0] = 42

In [80]:
In [82]: arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
In [83]: arr3d[0] = old_values

In [82]:
In [84]: arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
In [85]: arr3d[1, 0]

array([7, 8, 9])

In [84]:
In [86]: x = arr3d[1]

In [85]:
In [87]: x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
In [88]: x[0]

array([7, 8, 9])

In [87]:
In [89]: arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [88]:
In [90]: arr[1:6]

array([ 1,  2,  3,  4, 64])

In [89]:
In [91]: arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
In [92]: arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
In [93]: arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [93]:
In [94]: lower_dim_slice = arr2d[1, :2]

In [94]:
In [95]: lower_dim_slice.shape

(2,)

In [95]:
In [95]: lower_dim_slice.shape

(2,)

In [96]:
In [97]: arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [97]:
In [98]: arr2d[:2, 1:] = 0

In [98]:
In [99]: arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [99]:
In [100]: names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [100]:
In [101]: data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
   .....:                  [-12, -4], [3, 4]])

In [101]:
In [102]: names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [102]:
In [103]: data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [103]:
In [104]: names == "Bob"

array([ True, False, False,  True, False, False, False])

In [104]:
In [105]: data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [105]:
In [106]: data[names == "Bob", 1:]

array([[7],
       [0]])

In [106]:
In [107]: data[names == "Bob", 1]

array([7, 0])

In [107]:
In [108]: names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [108]:
In [109]: ~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [109]:
In [110]: data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [110]:
In [111]: cond = names == "Bob"

In [111]:
In [112]: data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [112]:
In [113]: mask = (names == "Bob") | (names == "Will")

In [113]:
In [114]: mask

array([ True, False,  True,  True,  True, False, False])

In [114]:
In [115]: data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [115]:
In [116]: data[data < 0] = 0

In [116]:
In [117]: data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [117]:
In [118]: data[names != "Joe"] = 7

In [118]:
In [119]: data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [119]:
In [120]: arr = np.zeros((8, 4))

In [120]:
In [121]: for i in range(8):
   .....:     arr[i] = i

In [121]:
In [122]: arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [122]:
In [123]: arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [123]:
In [124]: arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [124]:
In [125]: arr = np.arange(32).reshape((8, 4))

In [125]:
In [126]: arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [126]:
In [127]: arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [127]:
In [128]: arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [128]:
In [129]: arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [129]:
In [130]: arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [130]:
In [131]: arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [131]:
In [132]: arr = np.arange(15).reshape((3, 5))

In [132]:
In [134]: arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [133]:
In [135]: arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])

In [134]:
In [136]: arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [135]:
In [137]: np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [136]:
In [138]: arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [137]:
In [139]: arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [138]:
In [140]: arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])