In [2]:
In [7]: import numpy as np

In [3]:
In [8]: my_arr = np.arange(1_000_000)

In [4]:
In [9]: my_list = list(range(1_000_000))

In [7]:
In [10]: %timeit my_arr2 = my_arr * 2

763 μs ± 14.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
In [11]: %timeit my_list2 = [x * 2 for x in my_list]

25.1 ms ± 616 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
In [12]: import numpy as np

In [10]:
In [13]: data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [11]:
In [14]: data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [12]:
In [15]: data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [13]:
In [16]: data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [14]:
In [17]: data.shape

(2, 3)

In [15]:
In [18]: data.dtype

dtype('float64')

In [16]:
In [19]: data1 = [6, 7.5, 8, 0, 1]

In [17]:
In [20]: arr1 = np.array(data1)

In [18]:
In [21]: arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
In [22]: data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [20]:
In [23]: arr2 = np.array(data2)

In [21]:
In [24]: arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
In [25]: arr2.ndim

2

In [23]:
In [26]: arr2.shape

(2, 4)

In [24]:
In [27]: arr1.dtype

dtype('float64')

In [25]:
In [28]: arr2.dtype

dtype('int64')

In [26]:
In [29]: np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
In [30]: np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
In [31]: np.empty((2, 3, 2))

array([[[-3.10503618e+231, -1.44663096e-315],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  4.47032019e-038]],

       [[ 7.73184650e-091,  1.71696216e+185],
        [ 1.28241139e+160,  5.55149409e+170],
        [ 3.99910963e+252,  8.34402841e-309]]])

In [29]:
In [32]: np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
In [33]: arr1 = np.array([1, 2, 3], dtype=np.float64)

In [31]:
In [34]: arr2 = np.array([1, 2, 3], dtype=np.int32)

In [32]:
In [35]: arr1.dtype

dtype('float64')

In [33]:
In [36]: arr2.dtype

dtype('int32')

In [34]:
In [37]: arr = np.array([1, 2, 3, 4, 5])

In [35]:
In [38]: arr.dtype

dtype('int64')

In [36]:
In [39]: float_arr = arr.astype(np.float64)

In [37]:
In [40]: float_arr

array([1., 2., 3., 4., 5.])

In [38]:
In [41]: float_arr.dtype

dtype('float64')

In [39]:
In [42]: arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [40]:
In [43]: arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [41]:
In [44]: arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [60]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [44]:
In [47]: int_array = np.arange(10)

In [45]:
In [48]: calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [46]:
In [49]: int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
In [50]: zeros_uint32 = np.zeros(8, dtype="u4")

In [48]:
In [51]: zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [49]:
In [52]: arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [50]:
In [53]: arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [51]:
In [54]: arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [52]:
In [55]: arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
In [56]: 1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [54]:
In [57]: arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
In [58]: arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [56]:
In [59]: arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [57]:
In [60]: arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [58]:
In [61]: arr = np.arange(10)

In [59]:
In [62]: arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])